package com.example.demo1204.domain;

public class DiaryTags {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary_tags.diary_id
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    private Integer diaryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary_tags.tag_id
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    private Integer tagId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diary_tags.extras
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    private String extras;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary_tags.diary_id
     *
     * @return the value of diary_tags.diary_id
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    public Integer getDiaryId() {
        return diaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary_tags.diary_id
     *
     * @param diaryId the value for diary_tags.diary_id
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    public void setDiaryId(Integer diaryId) {
        this.diaryId = diaryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary_tags.tag_id
     *
     * @return the value of diary_tags.tag_id
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    public Integer getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary_tags.tag_id
     *
     * @param tagId the value for diary_tags.tag_id
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diary_tags.extras
     *
     * @return the value of diary_tags.extras
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    public String getExtras() {
        return extras;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diary_tags.extras
     *
     * @param extras the value for diary_tags.extras
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    public void setExtras(String extras) {
        this.extras = extras == null ? null : extras.trim();
    }
}