package com.example.demo1204.domain;

public class Tags {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tags._id
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tags.name
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tags.creator
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    private Integer creator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tags._id
     *
     * @return the value of tags._id
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tags._id
     *
     * @param id the value for tags._id
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tags.name
     *
     * @return the value of tags.name
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tags.name
     *
     * @param name the value for tags.name
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tags.creator
     *
     * @return the value of tags.creator
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tags.creator
     *
     * @param creator the value for tags.creator
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }
}