package com.example.demo1204.domain;

public class Users {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users._id
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.name
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.psw
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    private String psw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.sex
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.sign
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    private String sign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.photo
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    private String photo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.age
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    private Integer age;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users._id
     *
     * @return the value of users._id
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users._id
     *
     * @param id the value for users._id
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.name
     *
     * @return the value of users.name
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.name
     *
     * @param name the value for users.name
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.psw
     *
     * @return the value of users.psw
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    public String getPsw() {
        return psw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.psw
     *
     * @param psw the value for users.psw
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    public void setPsw(String psw) {
        this.psw = psw == null ? null : psw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.sex
     *
     * @return the value of users.sex
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.sex
     *
     * @param sex the value for users.sex
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.sign
     *
     * @return the value of users.sign
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.sign
     *
     * @param sign the value for users.sign
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    public void setSign(String sign) {
        this.sign = sign == null ? null : sign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.photo
     *
     * @return the value of users.photo
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.photo
     *
     * @param photo the value for users.photo
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.age
     *
     * @return the value of users.age
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.age
     *
     * @param age the value for users.age
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    public void setAge(Integer age) {
        this.age = age;
    }
}