package com.example.demo1204.mapper;

import com.example.demo1204.domain.DiaryTags;
import com.example.demo1204.domain.DiaryTagsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DiaryTagsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_tags
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    int countByExample(DiaryTagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_tags
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    int deleteByExample(DiaryTagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_tags
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    int insert(DiaryTags record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_tags
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    int insertSelective(DiaryTags record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_tags
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    List<DiaryTags> selectByExample(DiaryTagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_tags
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    int updateByExampleSelective(@Param("record") DiaryTags record, @Param("example") DiaryTagsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary_tags
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    int updateByExample(@Param("record") DiaryTags record, @Param("example") DiaryTagsExample example);
}