package com.example.demo1204.mapper;

import com.example.demo1204.domain.Diary;
import com.example.demo1204.domain.DiaryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
//要不在这里加@mapper，要不在启动的那个项目加上@mapperScan("包名")   
public interface DiaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    int countByExample(DiaryExample example);
    Diary selectDiaryMessageById(int id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    int deleteByExample(DiaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    int insert(Diary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    int insertSelective(Diary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    List<Diary> selectByExample(DiaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    Diary selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    int updateByExampleSelective(@Param("record") Diary record, @Param("example") DiaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    int updateByExample(@Param("record") Diary record, @Param("example") DiaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    int updateByPrimaryKeySelective(Diary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diary
     *
     * @mbggenerated Mon Dec 04 09:08:52 CST 2017
     */
    int updateByPrimaryKey(Diary record);
}